# Generated by Django 3.1.5 on 2021-06-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0026_auto_20210524_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='key',
        ),
        migrations.AddField(
            model_name='lesson',
            name='latlocation',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='longlocation',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
