# Generated by Django 3.1.5 on 2021-06-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0027_auto_20210626_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='latlocation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='longlocation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
